backend:
 name: git-gateway
 branch: master
 publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
 - name: "posts"
   label: "Posts"
   folder: "static/posts"
   slug: "{{slug}}"
	 create: true
   fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "posts" }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "date" }
    - { label: "Thumbnail", name: "thumbnail", widget: "image" }
    - { label: "Body", name: "body", widget: "markdown" }